---
- name: Check if kubeadm has been initialized
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeadm_initialized_status

- name: Copy the join command to control plane
  copy:
    mode: 0777
    src: /tmp/join-command-controller
    dest: /tmp/join-command.sh
  when: not kubeadm_initialized_status.stat.exists

- name: Join the control plane node to cluster
  command: sh /tmp/join-command.sh
  when: not kubeadm_initialized_status.stat.exists

- name: Removing join command
  file:
    path: /tmp/join-command.sh
    state: absent

- name: Create kubeconfig directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    group: ubuntu
    owner: ubuntu

- name: Writing kubeconfig manifest
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    group: ubuntu
    owner: ubuntu
    mode: 0600
    remote_src: true
