---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
  - /etc/containerd
  - /etc/systemd/system/containerd.service.d

- name: Writing configuration
  copy:
    src: files/containerd-config.toml
    dest: /etc/containerd/config.toml

- name: Writing proxy config
  template:
    src: templates/http-proxy.conf.j2
    dest: /etc/systemd/system/containerd.service.d/http-proxy.conf
    mode: 0644
  notify:
  - Restart service
