apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-local-dns-metrics
    k8s-app: node-local-dns
  name: node-local-dns-metrics
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9253
    protocol: TCP
    targetPort: 9253
  type: ClusterIP
  selector:
    k8s-app: node-local-dns
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: nodelocaldns
    app.kubernetes.io/part-of: nodelocaldns
  name: nodelocaldns
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: node-local-dns
