---
- name: Configure kubelet to use localhost kube-api
  replace:
    path: "{{ item }}"
    regexp: 'server: https://([0-9]{1,3}\.){3}[0-9]{1,3}:6443'
    replace: 'server: https://localhost:6443'
  with_items:
  - /etc/kubernetes/kubelet.conf
  - /etc/kubernetes/admin.conf
  - /home/ubuntu/.kube/config
  notify:
  - Restart Kubelet

- name: Secure Kubelet perimission
  file:
    path: "{{ item }}"
    mode: 0600
  with_items:
  - /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  - /var/lib/kubelet/config.yaml
