apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: control-plane
    component: etcd
  name: etcd-metrics
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
    targetPort: 2379
  type: ClusterIP
  selector:
    component: etcd
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    component: etcd
    app.kubernetes.io/part-of: control-plane
  name: etcd
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
    scheme: https
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
    tlsConfig:
      caFile: /etc/etcd-certs/ca.crt
      certFile: /etc/etcd-certs/client.crt
      keyFile: /etc/etcd-certs/client.key
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      component: etcd
