---
- name: Create directories
  file:
    path: /etc/nginx
    state: directory

- name: Writing configuration
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Writing static POD manifest
  copy:
    src: files/nginx.yaml
    dest: /etc/kubernetes/manifests
    mode: 0600

- name: Wait for Kubernetes API server to be ready
  wait_for:
    host: localhost
    port: 6443
    delay: 5
    timeout: 300

- name: Configure kubelet to use loadbalancer
  replace:
    path: /etc/kubernetes/kubelet.conf
    regexp: 'server: https://([0-9]{1,3}\.){3}[0-9]{1,3}:6443'
    replace: 'server: https://localhost:6443'
  notify:
  - Restart Kubelet
